# Generated by Django 3.1.5 on 2021-01-04 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Summoner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountId', models.CharField(max_length=56)),
                ('profileIconId', models.IntegerField()),
                ('revisionDate', models.BigIntegerField()),
                ('name', models.CharField(max_length=120)),
                ('summonerId', models.CharField(max_length=63)),
                ('puuid', models.CharField(max_length=78)),
                ('summonerLevel', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Timeline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameId', models.BigIntegerField()),
                ('data', models.JSONField()),
                ('summoner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riotwrapper.summoner')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameId', models.BigIntegerField()),
                ('data', models.JSONField()),
                ('summoner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riotwrapper.summoner')),
            ],
        ),
    ]
