# Generated by Django 3.1.5 on 2021-01-08 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('riotwrapper', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='summoner',
            unique_together={('accountId',)},
        ),
    ]
